// Stamps the build: a short hash of every source file the game runs on, written
// to public/shared/version.js. The browser and the compartment server both import
// it, so a page left open across a deploy can tell that the server moved on.
//
// Runs on every `wrangler deploy` and `wrangler dev` (build.command in
// wrangler.jsonc) and before `npm test`. The output is generated, so it is not
// committed.
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const OUT = join(ROOT, "public", "shared", "version.js");
const KINDS = /\.(js|mjs|html|css)$/;

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (KINDS.test(name) && p !== OUT) out.push(p);
  }
  return out;
}

const files = [...walk(join(ROOT, "public")), ...walk(join(ROOT, "src"))]
  .map((p) => relative(ROOT, p).split(sep).join("/"))
  .sort();
const hash = createHash("sha256");
for (const f of files) {
  hash.update(f + "\0");
  // line endings differ between a Windows checkout and the file as committed: hash the text, not the bytes
  hash.update(readFileSync(join(ROOT, f), "utf8").replace(/\r\n/g, "\n") + "\0");
}
const version = hash.digest("hex").slice(0, 10);
const body = `// Generated by tools/stamp.mjs from ${files.length} source files. Do not edit.\nexport const VERSION = "${version}";\n`;
let old = "";
try { old = readFileSync(OUT, "utf8"); } catch {}
if (old !== body) writeFileSync(OUT, body);
console.log("version " + version + " (" + files.length + " files)");
